package com.celecavac.advent2019;

public class Inputs {
    public static String input1 = "MB5)V1S\n" +
            "VYJ)JRF\n" +
            "SLW)9YR\n" +
            "CPL)8KQ\n" +
            "Q5P)H7W\n" +
            "TJT)139\n" +
            "PYD)XMX\n" +
            "4S5)K2V\n" +
            "RWW)JTL\n" +
            "HNC)81N\n" +
            "64N)V96\n" +
            "RRM)FXW\n" +
            "Y8R)1C1\n" +
            "VL8)M6N\n" +
            "G7L)RQJ\n" +
            "5C3)SC4\n" +
            "JZL)DGX\n" +
            "C7B)KSS\n" +
            "2X5)5YY\n" +
            "W91)5R1\n" +
            "KP8)QYY\n" +
            "NCL)5WX\n" +
            "HN9)4LZ\n" +
            "4Z6)15F\n" +
            "LHJ)B7D\n" +
            "S3S)J8Z\n" +
            "ZCW)KC1\n" +
            "3TJ)2RP\n" +
            "J9F)SXH\n" +
            "SHX)WH9\n" +
            "M4M)6NK\n" +
            "23F)Q7S\n" +
            "B7Y)ZM5\n" +
            "M7H)D8G\n" +
            "N8F)K1F\n" +
            "5PV)SXD\n" +
            "HGX)5BM\n" +
            "LH8)C2L\n" +
            "XFM)ZHM\n" +
            "H1L)XYG\n" +
            "4VH)W46\n" +
            "2Q8)6V5\n" +
            "G41)LNT\n" +
            "GNY)Y8R\n" +
            "95L)MJC\n" +
            "FPR)X8M\n" +
            "MS4)YL4\n" +
            "B8B)YL6\n" +
            "6N4)SWY\n" +
            "B65)X7B\n" +
            "N15)C89\n" +
            "LX4)TBZ\n" +
            "3W2)JRH\n" +
            "MVN)34C\n" +
            "XMX)DW8\n" +
            "221)5CM\n" +
            "QPP)14R\n" +
            "SRB)7SK\n" +
            "3P9)MKR\n" +
            "DGX)6FT\n" +
            "GQG)T3J\n" +
            "JS4)XTJ\n" +
            "9MQ)FKR\n" +
            "B29)PWB\n" +
            "XHC)NX1\n" +
            "55D)YCV\n" +
            "CV2)3FH\n" +
            "QN1)MFX\n" +
            "P2B)B51\n" +
            "Z4D)Z2S\n" +
            "3MZ)GYC\n" +
            "LCQ)FF9\n" +
            "VPZ)CV2\n" +
            "Z4D)K9P\n" +
            "9F2)CV6\n" +
            "NJS)HRR\n" +
            "W7Z)6CL\n" +
            "7NL)M9M\n" +
            "LJG)426\n" +
            "6LP)24X\n" +
            "YQ7)CXX\n" +
            "4RB)BKC\n" +
            "KNW)2X5\n" +
            "KCY)4D2\n" +
            "2GC)GV9\n" +
            "YWN)DWL\n" +
            "JML)131\n" +
            "JHR)3G4\n" +
            "KBM)BMX\n" +
            "GWB)S1P\n" +
            "LMW)2LL\n" +
            "DS7)8X3\n" +
            "8KT)ZCW\n" +
            "MHT)9XZ\n" +
            "MV8)B7Y\n" +
            "VPB)KT8\n" +
            "6RQ)87P\n" +
            "RP6)7QR\n" +
            "KQP)PXT\n" +
            "GBG)LCQ\n" +
            "CLY)RVF\n" +
            "64S)VP8\n" +
            "FR9)K5X\n" +
            "K37)QJK\n" +
            "9ZB)MS1\n" +
            "V6C)CXT\n" +
            "SC2)VJS\n" +
            "B45)9KK\n" +
            "ZH9)VWY\n" +
            "R17)XLS\n" +
            "N5Z)KWV\n" +
            "QWH)HY7\n" +
            "2LL)79J\n" +
            "1DF)RT5\n" +
            "MGH)XD4\n" +
            "VZ3)9YW\n" +
            "413)17F\n" +
            "YL4)15X\n" +
            "ZJB)SHX\n" +
            "HGF)VN7\n" +
            "4TW)TGX\n" +
            "3N4)SDF\n" +
            "KLJ)2FR\n" +
            "J5R)JZL\n" +
            "B59)WW6\n" +
            "KRX)JGM\n" +
            "N75)78C\n" +
            "T4B)H2H\n" +
            "2VB)JG3\n" +
            "7MG)4N2\n" +
            "C7M)2BK\n" +
            "MKR)LBF\n" +
            "KFX)6KG\n" +
            "48T)844\n" +
            "H1W)9XX\n" +
            "TGX)PN7\n" +
            "GGK)22B\n" +
            "M8N)GNY\n" +
            "L6R)WVW\n" +
            "VRY)B15\n" +
            "9YR)6RQ\n" +
            "QQ6)1KB\n" +
            "R22)STY\n" +
            "KC1)6RW\n" +
            "Q5Z)849\n" +
            "XWK)VFW\n" +
            "GFD)C8Z\n" +
            "L5D)J2Y\n" +
            "74R)3TJ\n" +
            "D94)3P9\n" +
            "JRH)HKV\n" +
            "3DZ)CFH\n" +
            "WKN)44S\n" +
            "JJC)9MQ\n" +
            "VKT)VBW\n" +
            "KT8)M7P\n" +
            "NH8)FDG\n" +
            "F7N)7MG\n" +
            "6RQ)RQM\n" +
            "V4T)ZN8\n" +
            "25C)2L3\n" +
            "WJW)DG9\n" +
            "N5X)SRB\n" +
            "QZK)GLJ\n" +
            "WG4)K56\n" +
            "844)J3V\n" +
            "HGX)KMR\n" +
            "87P)HKX\n" +
            "MK1)WTY\n" +
            "PC3)4TR\n" +
            "LG8)B29\n" +
            "SDR)FWN\n" +
            "9ZM)SVT\n" +
            "3K3)XJ6\n" +
            "WV1)G41\n" +
            "NKV)36R\n" +
            "WFG)4M1\n" +
            "WVW)1TQ\n" +
            "NQD)WF1\n" +
            "B9Q)3YV\n" +
            "CTP)VZB\n" +
            "72S)NSM\n" +
            "755)X7S\n" +
            "MB2)JWB\n" +
            "GD8)HGX\n" +
            "3FH)Q1H\n" +
            "P8P)TD2\n" +
            "8XK)KP8\n" +
            "1B4)7LK\n" +
            "3WC)LXK\n" +
            "YZP)QZK\n" +
            "C72)1M6\n" +
            "VZB)LZV\n" +
            "TC6)4RB\n" +
            "DH6)LJG\n" +
            "6XL)SKB\n" +
            "G52)3MZ\n" +
            "THK)F8F\n" +
            "S1P)NJK\n" +
            "QPG)5NF\n" +
            "9J8)W5V\n" +
            "6CJ)BY3\n" +
            "F8F)L4S\n" +
            "L7X)4P2\n" +
            "9NQ)RWW\n" +
            "V4V)BSC\n" +
            "YJW)G7F\n" +
            "3CK)GMH\n" +
            "VYR)LRM\n" +
            "XXP)JML\n" +
            "Z1S)3QH\n" +
            "3SH)YBF\n" +
            "WTY)QR4\n" +
            "FZ2)BMB\n" +
            "JZ5)Z5Q\n" +
            "HDZ)2V9\n" +
            "CTK)HRP\n" +
            "VWY)9HX\n" +
            "YNN)Z5F\n" +
            "N97)P1K\n" +
            "8NJ)JBK\n" +
            "VF7)JD2\n" +
            "4GG)KC6\n" +
            "8KS)YJ6\n" +
            "DH2)HXL\n" +
            "HB3)1HK\n" +
            "K56)DFB\n" +
            "4H6)K6Y\n" +
            "M7P)3WC\n" +
            "DG9)88R\n" +
            "VRB)Y2X\n" +
            "NMZ)RRS\n" +
            "T3J)NQ6\n" +
            "KYZ)KYX\n" +
            "TNN)48T\n" +
            "SG7)83G\n" +
            "JCK)QFN\n" +
            "5HH)1B4\n" +
            "16R)C4S\n" +
            "CQJ)KCS\n" +
            "6PH)2W6\n" +
            "89Q)7SB\n" +
            "NNK)L9J\n" +
            "77G)KTN\n" +
            "S2C)YOU\n" +
            "KFK)57L\n" +
            "LJ5)1BV\n" +
            "CCB)XQ8\n" +
            "14R)T7Y\n" +
            "3W2)TYQ\n" +
            "KNC)KF6\n" +
            "TW1)N5Z\n" +
            "ZCQ)8NJ\n" +
            "89G)5XD\n" +
            "Z15)SMZ\n" +
            "R5C)VMJ\n" +
            "CTJ)QWH\n" +
            "5NF)G52\n" +
            "24X)SBP\n" +
            "Z4K)HN9\n" +
            "6KG)BLM\n" +
            "66N)152\n" +
            "CCX)TTM\n" +
            "P1X)3CM\n" +
            "Q7Q)KYZ\n" +
            "VFL)LX4\n" +
            "SCT)KJ7\n" +
            "5VK)R8D\n" +
            "MKH)RZ4\n" +
            "H2H)WKN\n" +
            "6V5)9TW\n" +
            "W4G)QLS\n" +
            "LZV)D82\n" +
            "RHL)CLG\n" +
            "QG8)LX2\n" +
            "7S1)B7T\n" +
            "BY3)CMC\n" +
            "HBP)RD7\n" +
            "9PR)FVP\n" +
            "72J)Y14\n" +
            "PMM)8ZV\n" +
            "MZ8)MFN\n" +
            "3GD)8Y5\n" +
            "ZJ3)WJW\n" +
            "5HZ)X2V\n" +
            "FYZ)G5R\n" +
            "WMR)WT8\n" +
            "HNZ)6GW\n" +
            "9XX)33J\n" +
            "6QS)58X\n" +
            "11L)VWW\n" +
            "4LZ)MQT\n" +
            "MQT)PYS\n" +
            "BM6)YRP\n" +
            "658)LG8\n" +
            "NGZ)1VD\n" +
            "HRK)ZVG\n" +
            "RZG)RPJ\n" +
            "83G)B7B\n" +
            "JG3)BLQ\n" +
            "2SG)MQ4\n" +
            "B6C)4V6\n" +
            "GLJ)ST5\n" +
            "7MQ)P9X\n" +
            "3Y9)1ZB\n" +
            "K9P)D9Y\n" +
            "CJ8)LM6\n" +
            "KCY)VYJ\n" +
            "GVY)18R\n" +
            "SZG)QCX\n" +
            "15F)S5F\n" +
            "35W)YST\n" +
            "9NQ)BYJ\n" +
            "VGX)8LH\n" +
            "WQM)2HT\n" +
            "QR4)ZLF\n" +
            "SWY)HWK\n" +
            "P9X)HY6\n" +
            "LGH)ZJ4\n" +
            "GYC)NGZ\n" +
            "81F)P4T\n" +
            "9BF)CTF\n" +
            "5Q1)1RC\n" +
            "6MR)3X6\n" +
            "9HX)X83\n" +
            "DBQ)C9D\n" +
            "1KP)9F2\n" +
            "J8Z)JCK\n" +
            "Z5R)S2Z\n" +
            "B7B)KRX\n" +
            "ZM5)1YF\n" +
            "H2N)G5C\n" +
            "FSR)9ZM\n" +
            "3YV)74R\n" +
            "93T)MCN\n" +
            "5HK)MVS\n" +
            "V22)4Z6\n" +
            "RSG)N15\n" +
            "YDJ)F9N\n" +
            "K6Y)RSZ\n" +
            "3CM)169\n" +
            "F2L)39W\n" +
            "CK4)842\n" +
            "G6Q)S1W\n" +
            "D3H)55D\n" +
            "842)YCL\n" +
            "NXQ)L67\n" +
            "KG8)NDS\n" +
            "LGD)2QJ\n" +
            "MFX)JLD\n" +
            "1KB)Z4D\n" +
            "RMW)CWB\n" +
            "LC2)QC1\n" +
            "Q36)HTW\n" +
            "SG7)CJX\n" +
            "9BH)N34\n" +
            "85F)YNF\n" +
            "LVD)9BH\n" +
            "7GL)KNC\n" +
            "SDF)C1Z\n" +
            "68R)WQC\n" +
            "BPW)N8F\n" +
            "3G4)71T\n" +
            "JFJ)CR2\n" +
            "YFD)6CJ\n" +
            "Q8N)XMD\n" +
            "2CV)X3M\n" +
            "NPZ)89Q\n" +
            "SSK)9TP\n" +
            "QC1)VPZ\n" +
            "CML)9MV\n" +
            "4NC)GVY\n" +
            "T26)9NQ\n" +
            "8Y5)TDB\n" +
            "TTM)9PR\n" +
            "7ZY)3XT\n" +
            "MQL)PXS\n" +
            "LXK)2SG\n" +
            "FWP)LBD\n" +
            "CSY)C72\n" +
            "FYQ)B2F\n" +
            "VYJ)SX8\n" +
            "ZHV)6QS\n" +
            "KKB)1ZM\n" +
            "XRN)6XL\n" +
            "VN4)6XV\n" +
            "KWV)KW5\n" +
            "SBP)971\n" +
            "BMX)FXV\n" +
            "7K4)L65\n" +
            "7XV)791\n" +
            "DW8)RSK\n" +
            "9XZ)5CD\n" +
            "KG8)5C3\n" +
            "LBD)WZ3\n" +
            "7DC)T4B\n" +
            "1J7)XN9\n" +
            "KF6)GJR\n" +
            "TPV)FR9\n" +
            "B7T)89F\n" +
            "F94)KLB\n" +
            "3CV)49V\n" +
            "PN7)J89\n" +
            "CLY)F2P\n" +
            "71Z)YZP\n" +
            "HRR)X9Z\n" +
            "1SF)QQ6\n" +
            "MKR)5P3\n" +
            "XLB)G3P\n" +
            "3XT)6FC\n" +
            "WSC)TR9\n" +
            "1SF)8JZ\n" +
            "YMK)7T6\n" +
            "YLW)Q9Y\n" +
            "LQC)FSX\n" +
            "971)9LV\n" +
            "PL3)MMV\n" +
            "78C)Q72\n" +
            "NS8)W6M\n" +
            "RPW)5YW\n" +
            "91Q)QKC\n" +
            "B9B)7Q4\n" +
            "Q3J)B2D\n" +
            "2ZP)YMK\n" +
            "MSS)RP6\n" +
            "N6H)X4V\n" +
            "5P3)PHS\n" +
            "7LP)VXP\n" +
            "FJT)251\n" +
            "N9G)N71\n" +
            "21W)XRJ\n" +
            "FFT)Z22\n" +
            "89F)VRY\n" +
            "45S)MZ8\n" +
            "8J5)98X\n" +
            "4YF)HCN\n" +
            "3X6)WFG\n" +
            "R8D)THY\n" +
            "YNS)KT3\n" +
            "2TZ)W6V\n" +
            "MFN)P6B\n" +
            "1HK)WSV\n" +
            "PXS)YQ7\n" +
            "7LJ)PKH\n" +
            "QHG)4TW\n" +
            "G16)7QV\n" +
            "CXX)GL5\n" +
            "KDN)NNT\n" +
            "TPS)JZ3\n" +
            "X7B)RSG\n" +
            "6B1)JKD\n" +
            "CLG)ZGY\n" +
            "WQC)QTP\n" +
            "MYZ)3N4\n" +
            "Y8R)KMW\n" +
            "YL6)45S\n" +
            "H25)459\n" +
            "9TW)M3N\n" +
            "HDF)SLJ\n" +
            "LX2)5V6\n" +
            "6SD)2ZC\n" +
            "KGQ)XWK\n" +
            "85H)7ZV\n" +
            "459)XGH\n" +
            "VWW)M4M\n" +
            "27C)CTP\n" +
            "RKV)FSR\n" +
            "Z5K)9L1\n" +
            "2P1)6N1\n" +
            "WZ3)D94\n" +
            "TF1)CV3\n" +
            "1YF)T3S\n" +
            "F87)N9D\n" +
            "H7Z)QPP\n" +
            "NDS)GP1\n" +
            "GLN)R5Q\n" +
            "BHV)XRN\n" +
            "4T5)658\n" +
            "QRF)HW8\n" +
            "Q66)WWZ\n" +
            "2Q6)DWD\n" +
            "7T6)L9V\n" +
            "RVF)MXJ\n" +
            "RZ4)WQM\n" +
            "V9T)SR2\n" +
            "M21)CTK\n" +
            "ZDW)QP4\n" +
            "WF1)VRB\n" +
            "VXR)KFX\n" +
            "NHR)HDF\n" +
            "11P)TG5\n" +
            "K2V)YGJ\n" +
            "NH3)V76\n" +
            "VNQ)WY7\n" +
            "G8P)8YY\n" +
            "W5C)RZG\n" +
            "W46)T73\n" +
            "C89)N5X\n" +
            "2V9)5FQ\n" +
            "P5K)NCL\n" +
            "DNK)98T\n" +
            "FLX)MB5\n" +
            "VXG)R17\n" +
            "YQ7)Q36\n" +
            "L67)K62\n" +
            "74G)28S\n" +
            "X9H)L6R\n" +
            "JRH)CJ6\n" +
            "LBJ)JHR\n" +
            "SX8)TF1\n" +
            "RD7)3P3\n" +
            "H4X)KPW\n" +
            "J33)BWF\n" +
            "R4G)VXR\n" +
            "XRJ)Y25\n" +
            "Q7Q)GD8\n" +
            "2SG)P1X\n" +
            "4CB)66N\n" +
            "VYW)FF1\n" +
            "YB6)CL1\n" +
            "4QG)TX6\n" +
            "PKH)FYQ\n" +
            "JPG)LL9\n" +
            "M8W)RGV\n" +
            "XF9)NNK\n" +
            "COM)Q1M\n" +
            "SMZ)DS7\n" +
            "DNP)68R\n" +
            "1V4)4KY\n" +
            "GDN)NHR\n" +
            "8D1)HCL\n" +
            "KC6)HGF\n" +
            "CPS)VFL\n" +
            "33K)XQZ\n" +
            "Y14)RJ6\n" +
            "H3F)77G\n" +
            "NMG)F7N\n" +
            "FWN)3GD\n" +
            "36R)MZ3\n" +
            "MG8)VGX\n" +
            "6CL)352\n" +
            "JM4)FRB\n" +
            "43X)RNH\n" +
            "TBW)F8R\n" +
            "JCZ)V22\n" +
            "11Q)W7Z\n" +
            "N1L)RVD\n" +
            "Q6V)DNP\n" +
            "BWF)Y9G\n" +
            "H8D)D13\n" +
            "F8R)4QR\n" +
            "J1X)8X4\n" +
            "XFJ)N35\n" +
            "QTP)869\n" +
            "G3P)11Q\n" +
            "K9L)QYX\n" +
            "KN6)XHC\n" +
            "MWF)G6Q\n" +
            "KTN)SYM\n" +
            "XGH)8MN\n" +
            "QPP)W52\n" +
            "G2Y)FBZ\n" +
            "WBX)ZQ4\n" +
            "4F7)7XV\n" +
            "152)KGQ\n" +
            "CJX)L5D\n" +
            "JZ3)4ZT\n" +
            "CCB)N9G\n" +
            "HK7)K4Q\n" +
            "JGH)MGH\n" +
            "VN7)PH4\n" +
            "M9Z)S9V\n" +
            "SK8)PYD\n" +
            "3V9)G45\n" +
            "ZN8)4QG\n" +
            "2Q6)HLM\n" +
            "D13)LYH\n" +
            "ZQ4)D6G\n" +
            "SVT)SDR\n" +
            "PFK)QZ4\n" +
            "CXT)X31\n" +
            "44S)5GB\n" +
            "1RC)PKD\n" +
            "LWT)G7L\n" +
            "RX1)VRQ\n" +
            "P31)WYC\n" +
            "47S)NMG\n" +
            "C1Z)YY5\n" +
            "HWK)GGK\n" +
            "JC5)1GW\n" +
            "HVX)395\n" +
            "W6M)VF7\n" +
            "JTL)4GD\n" +
            "G5C)7BN\n" +
            "PQL)GMS\n" +
            "NXQ)45D\n" +
            "S5S)HNZ\n" +
            "C12)K2D\n" +
            "7P9)282\n" +
            "QF5)3W2\n" +
            "WH4)9VJ\n" +
            "YNF)M8W\n" +
            "5V6)DX7\n" +
            "XQZ)7D2\n" +
            "XTJ)HM5\n" +
            "HTR)9H5\n" +
            "HYN)71Z\n" +
            "7Q4)TF3\n" +
            "WH9)GF2\n" +
            "1CG)Q5Z\n" +
            "5GB)S3S\n" +
            "WFF)DJT\n" +
            "N4C)5BJ\n" +
            "32D)XB5\n" +
            "KLB)SC2\n" +
            "15X)1C3\n" +
            "GDT)W3X\n" +
            "1GW)CKZ\n" +
            "GGJ)4W8\n" +
            "5BJ)H7Z\n" +
            "PPT)7S1\n" +
            "FY4)SCM\n" +
            "395)3K3\n" +
            "HFT)K98\n" +
            "2RP)LZ4\n" +
            "49V)4LH\n" +
            "F2T)GCL\n" +
            "DJR)VTW\n" +
            "QW3)M8N\n" +
            "LYH)VYW\n" +
            "6N1)4YF\n" +
            "N34)VKT\n" +
            "1KB)YFD\n" +
            "3YB)ZB6\n" +
            "RSZ)F2T\n" +
            "2FR)1V4\n" +
            "MDJ)Z4K\n" +
            "K62)TW1\n" +
            "J3V)NHJ\n" +
            "JML)GT8\n" +
            "6RW)8CP\n" +
            "8ZV)9BF\n" +
            "XXP)NMZ\n" +
            "K4Q)T36\n" +
            "L4S)22G\n" +
            "953)XFM\n" +
            "ZGY)HTR\n" +
            "RJ6)4H6\n" +
            "HRP)TQD\n" +
            "NNT)5YP\n" +
            "L65)1H8\n" +
            "KXB)8YB\n" +
            "T5D)P5K\n" +
            "LJY)VTL\n" +
            "SCS)HJ7\n" +
            "35S)2RZ\n" +
            "NX1)THK\n" +
            "HY7)36Z\n" +
            "FXV)369\n" +
            "RSK)4Z2\n" +
            "2Y8)F9B\n" +
            "NNW)KG7\n" +
            "WSV)78N\n" +
            "MMV)5GL\n" +
            "JLD)WSC\n" +
            "PZH)N7G\n" +
            "LL9)4Y4\n" +
            "1BV)BG2\n" +
            "XMD)NT6\n" +
            "H9D)XF9\n" +
            "MNV)W8J\n" +
            "SX8)V3N\n" +
            "P8Y)CW1\n" +
            "T73)3F9\n" +
            "D82)32Z\n" +
            "XPH)PLM\n" +
            "352)NL6\n" +
            "Z94)D43\n" +
            "NK7)7QT\n" +
            "N35)KHR\n" +
            "NM1)MG8\n" +
            "8JZ)TJT\n" +
            "923)G3N\n" +
            "MVS)7DH\n" +
            "YMK)HVQ\n" +
            "JM4)74G\n" +
            "HJ7)RPW\n" +
            "9CY)C7M\n" +
            "V76)4GG\n" +
            "LNT)Y2J\n" +
            "8WD)YNN\n" +
            "41X)GKF\n" +
            "TD2)FZ2\n" +
            "T6H)4TQ\n" +
            "NHB)NKV\n" +
            "TV3)RRM\n" +
            "VRM)LVD\n" +
            "QNZ)FJT\n" +
            "3KZ)P8P\n" +
            "XJ6)3Y9\n" +
            "4D5)YSS\n" +
            "WB3)TV3\n" +
            "1Y6)Q3J\n" +
            "98T)6WH\n" +
            "SLT)KQL\n" +
            "951)5N8\n" +
            "9ZB)Z6X\n" +
            "KKD)M4B\n" +
            "YGJ)4F1\n" +
            "KBV)PQL\n" +
            "G45)M7H\n" +
            "8CP)J9F\n" +
            "BLQ)2P1\n" +
            "XS6)NXQ\n" +
            "BZ9)XQK\n" +
            "YLN)D1R\n" +
            "55T)XQB\n" +
            "N7H)RFF\n" +
            "FTM)93T\n" +
            "LJ5)MZ9\n" +
            "3YB)BFP\n" +
            "X9Z)7K7\n" +
            "W8J)9BC\n" +
            "43X)NM1\n" +
            "G5R)JGH\n" +
            "7SK)HRK\n" +
            "3BL)SWS\n" +
            "N38)QL4\n" +
            "HKV)64S\n" +
            "SDF)W33\n" +
            "D94)HB3\n" +
            "GWW)8DQ\n" +
            "3QH)WFF\n" +
            "SLJ)2Y4\n" +
            "3TJ)NQT\n" +
            "1C3)KLJ\n" +
            "954)VL8\n" +
            "LW2)Z6D\n" +
            "2F1)RQ5\n" +
            "C1Z)XM7\n" +
            "3CV)5HH\n" +
            "QCK)QHS\n" +
            "XKD)2XP\n" +
            "24J)221\n" +
            "8KS)MF3\n" +
            "5YY)DJQ\n" +
            "KBH)1W7\n" +
            "XYG)XHV\n" +
            "XMW)BTK\n" +
            "B2D)5T2\n" +
            "2W6)DH6\n" +
            "W2R)CK4\n" +
            "FY4)9RH\n" +
            "WF1)L7G\n" +
            "6GW)LBJ\n" +
            "QCX)H25\n" +
            "XHV)3DZ\n" +
            "5Z7)N9H\n" +
            "RYD)H27\n" +
            "QVD)ZJ3\n" +
            "CM1)NHB\n" +
            "W8J)8KH\n" +
            "C5D)WV1\n" +
            "CV3)25C\n" +
            "953)741\n" +
            "9MV)ZCQ\n" +
            "WYC)SLW\n" +
            "6WH)387\n" +
            "FXW)1G1\n" +
            "Z1S)212\n" +
            "MS1)FYZ\n" +
            "W33)F78\n" +
            "NQT)72G\n" +
            "2XP)1MG\n" +
            "J9J)KBS\n" +
            "C1R)RHL\n" +
            "L7G)R4G\n" +
            "HWK)CCX\n" +
            "TNP)1SF\n" +
            "5R1)SLT\n" +
            "B51)VDS\n" +
            "FBK)LH2\n" +
            "387)XXP\n" +
            "4NX)RDL\n" +
            "FF9)XW7\n" +
            "D3P)5R5\n" +
            "M3N)YWW\n" +
            "2Q8)9FM\n" +
            "8YY)1J7\n" +
            "Z6X)3CV\n" +
            "9HX)FV8\n" +
            "8MN)S2C\n" +
            "XD4)5HK\n" +
            "ST7)B59\n" +
            "LR2)PF2\n" +
            "23Y)FTM\n" +
            "7D2)F2H\n" +
            "9JG)TG9\n" +
            "2QJ)H4J\n" +
            "HM5)CSY\n" +
            "DH5)55T\n" +
            "GFL)WBX\n" +
            "HGF)SK8\n" +
            "PXT)SCT\n" +
            "K2D)7J8\n" +
            "78K)MDJ\n" +
            "2XT)MP2\n" +
            "4QR)549\n" +
            "DFB)DRV\n" +
            "6NK)Q7Q\n" +
            "5BM)2Y8\n" +
            "9XZ)DT2\n" +
            "M25)MV8\n" +
            "2BK)3V9\n" +
            "28S)W2R\n" +
            "RPJ)X37\n" +
            "QLS)9XF\n" +
            "X83)XFJ\n" +
            "8X4)ZHV\n" +
            "KMR)KDN\n" +
            "2K2)4T5\n" +
            "LRM)MWF\n" +
            "JGM)4D5\n" +
            "4LH)PZH\n" +
            "L4X)H2N\n" +
            "HHH)C12\n" +
            "R4G)GWB\n" +
            "ZVP)F22\n" +
            "YBF)H37\n" +
            "RSY)PD7\n" +
            "K3W)VXG\n" +
            "K9G)HN8\n" +
            "1C1)QCK\n" +
            "YTK)JZ5\n" +
            "KQL)NLZ\n" +
            "PLM)H7X\n" +
            "PYS)GDT\n" +
            "TY2)VRM\n" +
            "FF9)SZY\n" +
            "SXH)SZG\n" +
            "2HT)P19\n" +
            "JTQ)B5F\n" +
            "B9B)F2L\n" +
            "5CM)CPS\n" +
            "L5D)GQG\n" +
            "K1F)QNZ\n" +
            "7QT)LJY\n" +
            "9KK)1DF\n" +
            "XN9)KBV\n" +
            "9VJ)SG7\n" +
            "M4B)ZDW\n" +
            "6XV)MQL\n" +
            "1VL)Z94\n" +
            "KSS)H8D\n" +
            "STY)JFJ\n" +
            "PXR)K3W\n" +
            "X3M)35W\n" +
            "RNH)FWP\n" +
            "2RZ)LW4\n" +
            "HVQ)QG8\n" +
            "8VS)QZS\n" +
            "M8T)4YM\n" +
            "GJR)SBJ\n" +
            "N9D)WH3\n" +
            "4TQ)VZ3\n" +
            "GG6)6MY\n" +
            "4TR)M21\n" +
            "XLS)6QC\n" +
            "MZ3)YWS\n" +
            "ZRG)HK7\n" +
            "V1S)ZRG\n" +
            "CR2)V8R\n" +
            "81N)PJX\n" +
            "VXP)LMZ\n" +
            "849)LTC\n" +
            "DWD)LQC\n" +
            "1H8)3FT\n" +
            "D2T)KG8\n" +
            "BYJ)5Q1\n" +
            "3H6)5X1\n" +
            "8KQ)CHK\n" +
            "T7Y)J1X\n" +
            "4GD)KQP\n" +
            "XM7)QF5\n" +
            "9RH)JZR\n" +
            "GKF)DBQ\n" +
            "THY)JHZ\n" +
            "5XD)2GC\n" +
            "MV8)HBP\n" +
            "CW1)W91\n" +
            "411)923\n" +
            "RRS)8XK\n" +
            "C66)TNP\n" +
            "BMX)J5R\n" +
            "FKR)5Z7\n" +
            "MRV)PFK\n" +
            "9BC)59G\n" +
            "GVY)GDN\n" +
            "HH8)DRK\n" +
            "V96)6B1\n" +
            "SKB)KFK\n" +
            "DJQ)23Y\n" +
            "PF2)2HD\n" +
            "2Y4)D3F\n" +
            "K86)K1P\n" +
            "YRP)GBG\n" +
            "V8R)W4G\n" +
            "F9N)GP8\n" +
            "XQB)BPW\n" +
            "CSY)C66\n" +
            "NHJ)D2T\n" +
            "GGF)MK1\n" +
            "4NX)V6C\n" +
            "JYC)YNS\n" +
            "GMS)KNG\n" +
            "XW7)MRV\n" +
            "RFS)Q2C\n" +
            "7NL)WH4\n" +
            "TBZ)FLX\n" +
            "RQ5)ZJB\n" +
            "FPX)WL3\n" +
            "BMB)K86\n" +
            "N7G)WC7\n" +
            "T3S)NQD\n" +
            "KG7)GLN\n" +
            "741)CPL\n" +
            "S1W)G8P\n" +
            "W5V)ZJJ\n" +
            "JRF)X8V\n" +
            "TX6)PK9\n" +
            "89Q)DFS\n" +
            "W6V)9FW\n" +
            "D8G)NVJ\n" +
            "VBW)3SH\n" +
            "VTW)RYD\n" +
            "5CM)QVD\n" +
            "9TP)LC2\n" +
            "NCD)4VH\n" +
            "HLM)11L\n" +
            "6MY)S68\n" +
            "S2Z)V3R\n" +
            "BFP)954\n" +
            "Z5R)YB6\n" +
            "SBP)2Q8\n" +
            "JWQ)TQK\n" +
            "F2T)VPB\n" +
            "SZY)PXR\n" +
            "ML1)ZH9\n" +
            "LM6)LH8\n" +
            "CV6)69H\n" +
            "77Y)G2Y\n" +
            "22B)JYC\n" +
            "4Z2)1G9\n" +
            "5N8)755\n" +
            "GCL)Q5P\n" +
            "4ZT)M8T\n" +
            "Z6H)RKV\n" +
            "ML1)M9B\n" +
            "4YM)LFL\n" +
            "9JG)LMW\n" +
            "3FT)2XT\n" +
            "RQM)B6C\n" +
            "DRV)1Y6\n" +
            "B1P)3YB\n" +
            "PGR)YDJ\n" +
            "9L1)RWV\n" +
            "79J)41X\n" +
            "GF8)YTK\n" +
            "N15)4S7\n" +
            "8MC)1VL\n" +
            "4F7)77Y\n" +
            "SYM)YHV\n" +
            "4P2)2PZ\n" +
            "426)2TZ\n" +
            "H7X)K37\n" +
            "17F)71V\n" +
            "9G9)PKR\n" +
            "KC2)N38\n" +
            "L4X)WB3\n" +
            "1TQ)G6B\n" +
            "YSS)SCS\n" +
            "Q1M)WW8\n" +
            "819)2CV\n" +
            "Q2C)B65\n" +
            "169)7P9\n" +
            "139)7DC\n" +
            "D43)LR2\n" +
            "KJ7)HH8\n" +
            "C4S)MHT\n" +
            "5G8)HDZ\n" +
            "QTK)J33\n" +
            "F2H)YBQ\n" +
            "5YP)YWN\n" +
            "W52)1SL\n" +
            "32Z)CM1\n" +
            "LZ4)2F1\n" +
            "7SB)QPG\n" +
            "7K7)SSY\n" +
            "CW1)9DN\n" +
            "YCL)LW2\n" +
            "CTF)N97\n" +
            "FV8)8KS\n" +
            "KQP)R1M\n" +
            "6QC)P2B\n" +
            "LW4)64N\n" +
            "R17)FQN\n" +
            "71V)4CB\n" +
            "X31)8VS\n" +
            "5FQ)9ZB\n" +
            "7J8)D8T\n" +
            "WZ3)KKB\n" +
            "VDS)WLZ\n" +
            "WT8)J9J\n" +
            "BKC)PC3\n" +
            "T4B)9G9\n" +
            "NT6)ST7\n" +
            "LH2)JCZ\n" +
            "QHS)RMW\n" +
            "9LV)PLL\n" +
            "16M)H1L\n" +
            "HCN)PMM\n" +
            "J69)8KT\n" +
            "35S)7JW\n" +
            "5C3)F6S\n" +
            "J89)LJ5\n" +
            "FVP)LHJ\n" +
            "RT5)XS6\n" +
            "LBF)QW3\n" +
            "8YB)GGF\n" +
            "ZHM)5HZ\n" +
            "W3X)MGQ\n" +
            "KHR)G16\n" +
            "HY6)DNW\n" +
            "CMC)VPJ\n" +
            "Q72)JMG\n" +
            "WW8)Z6H\n" +
            "Y25)72S\n" +
            "3MZ)53C\n" +
            "791)951\n" +
            "KPW)S5S\n" +
            "NQ6)QRF\n" +
            "NCL)VYR\n" +
            "1VD)85F\n" +
            "QYX)413\n" +
            "NJK)D3H\n" +
            "N74)MNV\n" +
            "MP2)F87\n" +
            "4F1)FQH\n" +
            "JZR)WMR\n" +
            "DNW)TNN\n" +
            "YZP)NH3\n" +
            "H27)FY4\n" +
            "28S)6R8\n" +
            "DRK)B9B\n" +
            "NTG)1FY\n" +
            "GL5)HVX\n" +
            "G3N)CML\n" +
            "CPS)PQN\n" +
            "R1M)TY2\n" +
            "C8Z)MS4\n" +
            "N71)ML1\n" +
            "5NF)GF8\n" +
            "SCM)CCB\n" +
            "BG2)9JG\n" +
            "ZVG)6SD\n" +
            "FBZ)BZ9\n" +
            "L9V)7ZY\n" +
            "7DH)B8B\n" +
            "1JT)DNK\n" +
            "QL4)NS8\n" +
            "7LK)35S\n" +
            "QKC)SAN\n" +
            "Q1H)DJR\n" +
            "4N2)C1R\n" +
            "SC4)R22\n" +
            "413)WG4\n" +
            "SXD)K9L\n" +
            "9CY)4S5\n" +
            "58X)NCD\n" +
            "VTL)LGH\n" +
            "V96)P31\n" +
            "KYH)CLY\n" +
            "LTC)MB2\n" +
            "D9Y)JM4\n" +
            "53C)F94\n" +
            "PD7)7MQ\n" +
            "5GL)6XW\n" +
            "6FT)H4X\n" +
            "RQJ)TC6\n" +
            "WH3)2VB\n" +
            "M6N)H66\n" +
            "369)N74\n" +
            "TF3)JC5\n" +
            "FGL)NTG\n" +
            "P6B)1JT\n" +
            "MDJ)V9T\n" +
            "6CL)754\n" +
            "V3N)2Q6\n" +
            "5YW)KCY\n" +
            "VRY)24J\n" +
            "2HD)47S\n" +
            "WL3)3YH\n" +
            "1SL)CTJ\n" +
            "QZ4)697\n" +
            "S68)KYH\n" +
            "KBS)FPR\n" +
            "DT2)H9D\n" +
            "CHK)Y3R\n" +
            "Y2X)L7X\n" +
            "9VJ)3CK\n" +
            "BLM)CQJ\n" +
            "PLL)81F\n" +
            "RFF)5VK\n" +
            "V3R)LWT\n" +
            "FQN)M25\n" +
            "9H5)KHG\n" +
            "KTN)4NX\n" +
            "QZS)23F\n" +
            "H7W)MKH\n" +
            "PKD)33K\n" +
            "F2P)MVN\n" +
            "G6B)GZ6\n" +
            "8LH)PGR\n" +
            "NLZ)78K\n" +
            "GFD)XPH\n" +
            "LFL)N7H\n" +
            "D8T)7Z1\n" +
            "X4V)R2D\n" +
            "D1R)Q6V\n" +
            "JV2)DH5\n" +
            "WLZ)411\n" +
            "352)C7B\n" +
            "T36)QWS\n" +
            "5R5)Q66\n" +
            "HKX)KC2\n" +
            "QL9)32D\n" +
            "M5Q)T6H\n" +
            "88R)M5Q\n" +
            "MF3)B1P\n" +
            "9YW)BM6\n" +
            "Y9G)VNQ\n" +
            "M9B)7GL\n" +
            "57L)YLN\n" +
            "HTW)PL3\n" +
            "1ZM)JWQ\n" +
            "1W7)FFT\n" +
            "SR2)YJW\n" +
            "BTK)XKD\n" +
            "P19)RSY\n" +
            "BSC)7LJ\n" +
            "212)NR2\n" +
            "LX4)K39\n" +
            "HXL)Z5R\n" +
            "FSX)W3T\n" +
            "HN8)FGL\n" +
            "KFK)27C\n" +
            "WN2)M9Z\n" +
            "F9B)GFL\n" +
            "WY7)Z15\n" +
            "GQL)21W\n" +
            "BZ9)KNW\n" +
            "MFS)9CY\n" +
            "GV9)NQN\n" +
            "V8T)91Q\n" +
            "D7X)GFD\n" +
            "4KY)Q8N\n" +
            "9NX)MFS\n" +
            "YB6)NK7\n" +
            "Q9Y)1KP\n" +
            "KCS)B45\n" +
            "M4B)GG6\n" +
            "ZVP)2K2\n" +
            "CWB)N3S\n" +
            "HVX)JTQ\n" +
            "59G)TTC\n" +
            "YMV)B9Q\n" +
            "16M)XLB\n" +
            "PJX)VN4\n" +
            "69H)11P\n" +
            "LMK)X9H\n" +
            "F6S)J69\n" +
            "R2D)5SJ\n" +
            "X37)17P\n" +
            "3CL)YMV\n" +
            "ST5)N4C\n" +
            "2L3)NH8\n" +
            "3F9)HNC\n" +
            "C2L)HFT\n" +
            "7QP)ZRM\n" +
            "C12)KN6\n" +
            "1V9)PPT\n" +
            "XB5)8J5\n" +
            "DJT)3BL\n" +
            "HKV)16M\n" +
            "YJ6)KBM\n" +
            "TX6)R5C\n" +
            "B15)LMK\n" +
            "549)JPG\n" +
            "K2V)NJS\n" +
            "FRB)1CG\n" +
            "MJC)4NC\n" +
            "TTC)H1W\n" +
            "KT3)CJ8\n" +
            "NR2)85H\n" +
            "131)3KZ\n" +
            "X8V)953\n" +
            "21W)W5C\n" +
            "3YH)8MC\n" +
            "VFW)7K4\n" +
            "D79)KXB\n" +
            "G7F)JJC\n" +
            "4M1)7NL\n" +
            "S9V)NPZ\n" +
            "VP8)K9G\n" +
            "KNG)HHH\n" +
            "D3F)T5D\n" +
            "SWS)3CL\n" +
            "TYQ)9NX\n" +
            "78N)N1L\n" +
            "RDL)819\n" +
            "X2V)L4X\n" +
            "8Y2)GQL\n" +
            "VRQ)FBK\n" +
            "1M6)QN1\n" +
            "MXJ)7LP\n" +
            "1MG)GTF\n" +
            "YY5)H3F\n" +
            "S5F)BHV\n" +
            "PHS)95L\n" +
            "6XW)72J\n" +
            "DFS)D7X\n" +
            "YWS)SSK\n" +
            "B1P)DH2\n" +
            "K98)FPX\n" +
            "Z5F)6N4\n" +
            "9DN)78H\n" +
            "W3T)JS4\n" +
            "7Z1)5G8\n" +
            "49V)9J8\n" +
            "Z6D)GGJ\n" +
            "V9T)MYZ\n" +
            "SC4)YLW\n" +
            "NQN)WN2\n" +
            "MFN)TBW\n" +
            "KRX)LGD\n" +
            "9FW)V8T\n" +
            "8X3)V4T\n" +
            "4S7)XMW\n" +
            "Y2J)5PV\n" +
            "QYY)T26\n" +
            "GMH)JV2\n" +
            "H98)Q2Y\n" +
            "MZ9)2ZP\n" +
            "ZRM)KBH\n" +
            "251)Z5K\n" +
            "KHG)HYN\n" +
            "5WX)P8Y\n" +
            "71T)N75\n" +
            "H37)6PH\n" +
            "HCL)D3P\n" +
            "M25)16R\n" +
            "K39)QL9\n" +
            "WWZ)8Y2\n" +
            "PK9)N6H\n" +
            "LMZ)ZVP\n" +
            "Z5Q)H98\n" +
            "JKD)WK2\n" +
            "JHZ)43X\n" +
            "PQN)NNW\n" +
            "J2Y)3H6\n" +
            "YWW)GWW\n" +
            "NL6)KKD\n" +
            "XQ8)TPS\n" +
            "RWV)8D1\n" +
            "TDB)RX1\n" +
            "2PZ)6MR\n" +
            "NSM)QTK\n" +
            "GP1)TPV\n" +
            "ZB6)1V9\n" +
            "QHG)4F7\n" +
            "18R)D79\n" +
            "ZJJ)Z1S\n" +
            "45D)7QP\n" +
            "7QV)X42\n" +
            "M9M)MSS\n" +
            "TQK)V4V\n" +
            "Q7S)23K\n" +
            "TG9)C5D\n" +
            "VMJ)89G\n" +
            "7QR)SPB\n" +
            "RGV)QHG\n" +
            "3P3)RFS\n" +
            "GT8)6LP\n" +
            "P1K)8WD\n";
}
